//Funciones para cambiar de idioma modificando el contenido de cada linea de texto
function english() {
    document.getElementById("ingles").style.display = "none";
    document.getElementById("español").style.display = "block";
    acercaDeMi.innerHTML = "Professional profile";
    educacionTitulo.innerHTML = "Education";
    exp.innerHTML = "Proyects";
    skill.innerHTML = "Habilities";
    curriculumTitulo.innerHTML = "Resume";
    contacto.innerHTML = "Contact";
    cargo.innerHTML = "Information Systems Engineering student";
    aboutMe.innerHTML = "<strong>Professional profile:</strong>";
    type.innerHTML = "Third-year Information Systems Engineering student at UTN with a background in programming, data structures, operating systems, and computer architecture. Seeking my first professional opportunity in the IT field to apply my knowledge, continue developing my technical skills, and contribute to the development of software solutions.";
    card.innerHTML = "<div><img src='Imagenes/integracion.png' alt='Integracion' class='img-titulos-sec'> Skills </div> <br> Languages: C (Intermediate), JavaScript (Basic), HTML, CSS <br> Tools: Git, GitHub, Visual Studio Code <br> Concepts: Data Structures, Object-Oriented Programming, Web Development <br> <br> <div> <img src='Imagenes/habilidad2.png' alt='Habilidades' class='img-titulos-sec'> Strengths: <div> <br> Analytical Thinking <br> Teamwork <br> Continuous Learning <br> Time Management" ;
    educacionSeccion.innerHTML = "Education:";
    card1.innerHTML = "Relevant Systems Courses: <br> • Algorithms and Data Structures <br> • Computer Architecture <br> • Operating Systems <br> • Systems Analysis <br> • Programming Paradigms (in progress) <br> • Programming Languages Syntax and Semantics (in progress) <br> • Data Communications (in progress)";
    am.innerHTML = "Information systems engineering";
    año_am.innerHTML = "2024 / Present";
    universidad.innerHTML = "National Technological University (Argentina)";
    cursoOracle.innerHTML = "Front-end developer course";
    añoCursoOracle.innerHTML = "March 2023 - September 2023";
    empresaCursoOracle.innerHTML = "ONE - Oracle Next Education";
    card2.innerHTML = "Completed formations: <hr> • Programming Fundamentals.<br> - Duration: 75 hours <hr> • HTML & CSS.<br> - Duration: 65 hours  <hr> • Business Agility.<br>  - Duration: 26 hours  <hr> • Front End.<br>  - Duration: 77 hours   <hr> • React.<br>  - Duration: 68 hours  <hr> • Entrepreneurship.<br>  - Duration: 45 hours";
    titulo_pagina.innerHTML = "<strong>Proyects:</strong>";
    encriptador.innerHTML = "Text Encryptor";
    portfolio.innerHTML = "My Portfolio";
    repositorio1.innerHTML = "GitHub Repository";
    repositorio2.innerHTML = "GitHub Repository";
    repositorio3.innerHTML = "GitHub Repository";
    repositorio4.innerHTML = "GitHub Repository";
    titulo_conocimientos.innerHTML = "<strong>technologies:</strong>";
    habilidades_principales.innerHTML = "Intermediate"
    habilidades_principiante.innerHTML = "Beginner"
    curriculumSpanish.innerHTML = "English Resume";
    curriculumEnglish.innerHTML = "Spanish Resume";
    formularioTitulo.innerHTML = "<strong>Contact Form:</strong>";
    nameForm.innerHTML = "Name:";
    validForm.innerHTML = "Valid data";
    invalidForm.innerHTML = "Please write your name";
    emailForm.innerHTML = "Email:";
    validForm1.innerHTML = "Valid data";
    invalidForm1.innerHTML = "Please write your email";
    asuntoForm.innerHTML = "Subject:";
    validForm2.innerHTML = "Valid data";
    invalidForm2.innerHTML = "Please write the subject";
    mensajeForm.innerHTML = "Message:";
    validForm3.innerHTML = "Valid data";
    invalidForm3.innerHTML = "Please write your message";
    sendForm.innerHTML = " Send form ";
  }
  
  function spanish() {
    document.getElementById("ingles").style.display = "block";
    document.getElementById("español").style.display = "none";
    acercaDeMi.innerHTML = "Perfil profesional";
    educacionTitulo.innerHTML = "Educación";
    exp.innerHTML = "Proyectos";
    skill.innerHTML = "Tecnologias";
    curriculumTitulo.innerHTML = "Curriculum"
    contacto.innerHTML = "Contacto";
    cargo.innerHTML = "Estudiante de Ingenieria En Sistemas De Información";
    aboutMe.innerHTML = "<strong>Perfil profesional:</strong>";
    type.innerHTML = "Estudiante de tercer año de Ingeniería en Sistemas de Información en la UTN, con formación en programación, estructuras de datos, sistemas operativos y arquitectura de computadoras. Busco mi primera experiencia profesional en el área de sistemas para aplicar mis conocimientos, seguir desarrollando mis habilidades técnicas y contribuir al desarrollo de soluciones de software.";
    card.innerHTML = "<div><img src='Imagenes/integracion.png' alt='Integracion' class='img-titulos-sec'>Habilidades:</div> <br> • Lenguajes: C (intermedio), JavaScript (basico), HTML, CSS. <br> • Herramientas: Git, GitHub, VSC. <br> • Conceptos: Estructuras de datos, Programación orientada a objetos, Desarrollo web <br> <br> <div> <img src='Imagenes/habilidad2.png' alt='Habilidades' class='img-titulos-sec'> Fortalezas: </div><br> • Pensamiento analítico<br> • Trabajo en equipo <br> • Aprendizaje continuo<br> • Gestion de tiempo";
    educacionSeccion.innerHTML = "Educación:";
    card1.innerHTML = "Materias relevantes de Sistemas:<br> • Algoritmos y Estructuras de Programación <br> • Arquitectura de Computadoras <br> • Sistemas Operativos <br> • Análisis de Sistemas <br> • Paradigmas de Programación (en curso) <br> • Sintaxis y Semántica de los Lenguajes (en curso) <br> • Comunicación de Datos (en curso)";
    am.innerHTML = "Ingenieria En Sistemas De Información";
    año_am.innerHTML = "2024 / Presente";
    universidad.innerHTML = "Universidad Tecnologica Nacional";
    cursoOracle.innerHTML = "Curso de desarrollador Front-End";
    añoCursoOracle.innerHTML = "Marzo 2023 - Septiembre 2023";
    empresaCursoOracle.innerHTML = "ONE - Oracle Next Education.";
    card2.innerHTML = "Formaciones finalizadas: <hr> • Principiante en programación.<br> - Duración: 75 Horas<br> <hr> • HTML & CSS.<br> - Duracion: 65 Horas<br> <hr> • Business Agility.<br> - Duracion: 26 Horas <hr> • Front End.<br> - Duracion: 77 Horas <hr> • React.<br> - Duracion: 68 Horas <hr> • Emprendimiento.<br> - Duracion: 45 Horas" ;
    titulo_pagina.innerHTML = "<strong>Proyectos:</strong>";
    encriptador.innerHTML = "Encriptador De Texto";
    portfolio.innerHTML = "Mi Portafolio";
    repositorio1.innerHTML = "Repositorio de GitHub";
    repositorio2.innerHTML = "Repositorio de GitHub";
    repositorio3.innerHTML = "Repositorio de GitHub";
    repositorio4.innerHTML = "Repositorio de GitHub";
    titulo_conocimientos.innerHTML = "<strong>Tecnologias :</strong";
    habilidades_principales.innerHTML = "intermedio";
    habilidades_principiante.innerHTML = "Principiante";
    curriculumSpanish.innerHTML = "Curriculum en Español";
    curriculumEnglish.innerHTML = "Curriculum en Ingles";
    formularioTitulo.innerHTML = "<strong>Formulario de contacto:</strong>";
    nameForm.innerHTML = "Nombre:";
    validForm.innerHTML = "Dato valido";
    invalidForm.innerHTML = "Por favor escriba su nombre";
    emailForm.innerHTML = "Correo electronico:";
    validForm1.innerHTML = "Dato valido";
    invalidForm1.innerHTML = "Por favor escriba su correo electronico";
    asuntoForm.innerHTML = "Asunto";
    validForm2.innerHTML = "Dato valido";
    invalidForm2.innerHTML = "Por favor escriba el asunto";
    mensajeForm.innerHTML = "Mensaje:";
    validForm3.innerHTML = "Dato valido";
    invalidForm3.innerHTML = "Por favor escriba su mensaje";
    sendForm.innerHTML = " Enviar formulario ";
  }
  