//Funciones para cambiar de idioma modificando el contenido de cada linea de texto
function english() {
    document.getElementById("ingles").style.display = "none";
    document.getElementById("español").style.display = "inline";
    acercaDeMi.innerHTML = "About Me"
    educacionTitulo.innerHTML = "Education"
    exp.innerHTML = "Programming experience"
    skill.innerHTML = "Skills"
    contacto.innerHTML = "Contact"
    cargo.innerHTML = "Front-End Junior Developer";
    age.innerHTML = "Age: 20 Years old"
    nationality.innerHTML = "Nationality: Argentina"
    aboutMe.innerHTML = "<strong>About me:</strong>"
    type.innerHTML = "During 2022, I studied the Multimedia Arts degree at the National University of the Arts. I had subjects like animation, art history, photography, etc. <br> One of the subjects I had was General Computing 1, where we learned HTML, CSS, JavaScript, and Bootstrap. While taking this subject, I realized that it was the only one I truly enjoyed. I could spend the whole day programming, and the hours would fly by effortlessly. I really enjoyed it. <br> By the end of the first year of my degree, I decided that I wanted to dedicate myself 100% to programming. This year, I started taking some courses like Alura Latam, Oracle, and Open Bootcamp, with the intention of starting a Systems Engineering program at the National Technological University in 2024."
    card.innerHTML = "Hobbies: <br> - I greatly enjoy music and sports, and I'm a passionate fitness enthusiast. I used to be a professional tennis player. <br> - I'm a cooking enthusiast, and I enjoy spending my weekends reading and watching movies/series. <br> <br> Soft skills: <br> • Flexibility, adaptability to change <br> • Effective communication skills <br> • Problem-solving abilities <br> • Teamwork <br> • Proactiveness <br> • Creativity <br> • Critical thinking <br>" 
    educacionSeccion.innerHTML = "Education:";
    card1.innerHTML = "• First year of the degree completed with an overall GPA of 8.17 (eight point seventeen). <br> • The degree includes subjects related to web development with JavaScript, CSS, and HTML, sound, animation, photography, programming with Processing, etc."
    am.innerHTML = "Bachelor of Multimedia Arts";
    año_am.innerHTML = "2022 / Present (First year finished)";
    universidad.innerHTML = "National University Of The Arts";
    cursoOracle.innerHTML = "Front-end developer course";
    cursoOP.innerHTML = "Front-end developer course";
    añoCursoOracle.innerHTML = "2023 / Present";
    añoCursoOP.innerHTML = "2023 / Present";
    empresaCursoOracle.innerHTML = "ONE - Oracle Next Education in association with Alura Latam.";
    card2.innerHTML = "Completed formations: <hr> • Personal Development: <br> - Duration: 35 Hours <br> <hr> • Beginner in Programming. <br> - Duration: 75 Hours <br> <hr> • HTML & CSS. <br> - Duration: 65 Hours <br> <hr> • Business Agility. <br> - Duration: 26 Hours"
    card3.innerHTML = "Completed formations: <hr> • Introduction to Programming. <br> - Duration: 9 Hours <br> <hr> • Concepts of Programming. <br> - Duration: 9 Hours <br> <hr> • HTML and CSS. <br> - Duration: 17 Hours <br> <hr> • Basic JavaScript. <br> - Duration: 15 Hours <br> <hr> • TypeScript. <br> - Duration: 9 Hours"
    card4.innerHTML = "• High school completed on time with an overall GPA of 8.51 (eight point fifty-one). <br> • Bachelor's degree in Popular Theater."
    colegio.innerHTML = "Bachelor of Popular Theater";
    numero_colegio.innerHTML = "School n° 788";
    titulo_pagina.innerHTML = "<strong>Programming experience:</strong>";
    encriptador.innerHTML = "Text Encryptor";
    repositorio.innerHTML = "GitHub Repository";
    github.innerHTML = "GitHub Repository";
    titulo_conocimientos.innerHTML = "<strong>Skills:</strong>";
    curriculumSpanish.innerHTML = "English curriculum"
    curriculumEnglish.innerHTML = "Spanish curriculum"
    formularioTitulo.innerHTML = "<strong>Contact Form:</strong>"
    nameForm.innerHTML = "Name:"
    validForm.innerHTML = "Valid data"
    invalidForm.innerHTML = "Please write your name"
    emailForm.innerHTML = "Email:"
    validForm1.innerHTML = "Valid data"
    invalidForm1.innerHTML = "Please write your email"
    asuntoForm.innerHTML = "Subject:"
    validForm2.innerHTML = "Valid data"
    invalidForm2.innerHTML = "Please write the subject"
    mensajeForm.innerHTML = "Message:"
    validForm3.innerHTML = "Valid data"
    invalidForm3.innerHTML = "Please write your message"
    sendForm.innerHTML = " Send form "
  }
  
  function spanish() {
    document.getElementById("ingles").style.display = "inline";
    document.getElementById("español").style.display = "none";
    acercaDeMi.innerHTML = "Acerca De Mi"
    educacionTitulo.innerHTML = "Educación"
    exp.innerHTML = "Experiencia Programacion"
    skill.innerHTML = "habilidades"
    contacto.innerHTML = "Contacto"
    cargo.innerHTML = "Desarrolador Front-End Junior";
    age.innerHTML = "Edad: 20 Años"
    nationality.innerHTML = "Nacionalidad: Argentina"
    aboutMe.innerHTML = "<strong>Acerca de mi:</strong>"
    type.innerHTML = "Durante 2022 estudié la carrera de artes multimediales de la universidad nacional de las artes. En ella tenía materias de sonido, animación, historia del arte, fotografía, etc. <br> Una de las materias que tenía era informática general 1, en la que vimos HTML, CSS, JavaScript y Bootstrap. Cursando esta materia me di cuenta de que era la única que realmente disfrutaba, que me podría pasar todo el día Programando y las horas se me pasaban como si nada, realmente lo disfrute. <br> Al finalizar el primer año de la licenciatura decidí que quería dedicarme al 100% a la programación, por lo que este año empece con algunos cursos como el de Alura Latam y Oracle o los de Open Bootcamp, con la intención de en el año 2024 iniciar una ingeniería en sistemas en la Universidad Tecnológica Nacional."
    card.innerHTML = "Hobbies: <br> - Disfruto mucho la musica y el deporte, gran apasionado del entrenamiento, ex tenista profesional.<br> - Apasionado de la cocina, disfruto pasar mis fines de semana leyendo y viendo peliculas/series. </br> <br> Soft skills:<br> • Flexibilidad, adaptacion al cambio<br> • Capacidad de comunicacion efectiva<br> • Resolucion de problemas<br> • Trabajo en equipo<br> • Proactividad<br> • Creatividad<br> • Pensamiento critico"
    educacionSeccion.innerHTML = "Educación:";
    card1.innerHTML = "• Primer año de la licenciatura finalizado con un promedio general de 8,17 (ocho con 17).<br> • En la licenciatura se estudian materias relacionadas al desarrollo web con JavaScript, CSS y HTML, sonido, animación, fotógrafia, programación con Processing, etc."
    am.innerHTML = "Licenciatura de Artes Multimediales";
    año_am.innerHTML = "2022 / Presente (Primer año finalizado)";
    universidad.innerHTML = "Universidad Nacional De Las Artes";
    cursoOracle.innerHTML = "Curso de desarrollador Front-End";
    cursoOP.innerHTML = "Curso de desarrollador Front-End";
    añoCursoOracle.innerHTML = "2023 / Presente";
    añoCursoOP.innerHTML = "2023 / Presente";
    empresaCursoOracle.innerHTML = "ONE - Oracle Next Education junto a Alura Latam.";
    card2.innerHTML = "Formaciones finalizadas: <hr> • Desarrollo personal.<br> - Duración: 35 Horas<br> <hr> • Principiante en programación.<br> - Duración: 75 Horas<br> <hr> • HTML & CSS.<br> - Duracion: 65 Horas<br> <hr> • Business Agility.<br> - Duracion: 26 Horas" 
    card3.innerHTML = " Formaciones finalizadas: <hr> • Introduccion a la programacion.<br> - Duración: 9 Horas<br> <hr> • Conceptos de la programacion.<br> - Duracion: 9 Horas<br> <hr> • HTML y CSS<br> - Duración: 17 Horas<br> <hr> • JavaScript Basico<br> - Duración: 15 Horas<br> <hr> • TypeScript<br> - Duracion: 9 Horas"
    card4.innerHTML = "• Colegio secundario finalizado en tiempo y forma con un promedio general de 8.51 (Ocho con cincuenta y uno) <br> • Bachillerato en teatro popular"
    colegio.innerHTML = "Bachiller en Teatro Popular";
    numero_colegio.innerHTML = "Colegio n° 788";
    titulo_pagina.innerHTML = "<strong>Experiencia en programacion:</strong>";
    encriptador.innerHTML = "Encriptador De Texto";
    repositorio.innerHTML = "Repositorio de GitHub";
    github.innerHTML = "Repositorio de GitHub";
    titulo_conocimientos.innerHTML = "<strong>Habilidades:</strong";
    curriculumSpanish.innerHTML = "Curriculum en Español"
    curriculumEnglish.innerHTML = "Curriculum en Ingles"
    formularioTitulo.innerHTML = "<strong>Formulario de contacto:</strong>"
    nameForm.innerHTML = "Nombre:"
    validForm.innerHTML = "Dato valido"
    invalidForm.innerHTML = "Por favor escriba su nombre"
    emailForm.innerHTML = "Correo electronico:"
    validForm1.innerHTML = "Dato valido"
    invalidForm1.innerHTML = "Por favor escriba su correo electronico"
    asuntoForm.innerHTML = "Asunto"
    validForm2.innerHTML = "Dato valido"
    invalidForm2.innerHTML = "Por favor escriba el asunto"
    mensajeForm.innerHTML = "Mensaje:"
    validForm3.innerHTML = "Dato valido"
    invalidForm3.innerHTML = "Por favor escriba su mensaje"
    sendForm.innerHTML = " Enviar formulario "
  }
  