//Funciones para cambiar de idioma modificando el contenido de cada linea de texto
function english() {
    document.getElementById("ingles").style.display = "none";
    document.getElementById("español").style.display = "inline";
    acercaDeMi.innerHTML = "Professional profile"
    educacionTitulo.innerHTML = "Education"
    exp.innerHTML = "Programming experience"
    skill.innerHTML = "Habilities"
    contacto.innerHTML = "Contact"
    cargo.innerHTML = "Information Systems Engineering student";
    aboutMe.innerHTML = "<strong>Professional profile:</strong>"
    type.innerHTML = "Third-year Information Systems Engineering student at UTN with a background in programming, data structures, operating systems, and computer architecture. Seeking my first professional opportunity in the IT field to apply my knowledge, continue developing my technical skills, and contribute to the development of software solutions."
    card.innerHTML = "Habilities: <br> - I greatly enjoy music and sports, and I'm a passionate fitness enthusiast. I used to be a professional tennis player. <br> - I'm a cooking enthusiast, and I enjoy spending my weekends reading and watching movies/series. <br> <br> Soft skills: <br> • Flexibility, adaptability to change <br> • Effective communication skills <br> • Problem-solving abilities <br> • Teamwork <br> • Proactiveness <br> • Creativity <br> • Critical thinking <br>" 
    educacionSeccion.innerHTML = "Education:";
    card1.innerHTML = "• First year of the degree completed with an overall GPA of 8.17 (eight point seventeen). <br> • The degree includes subjects related to web development with JavaScript, CSS, and HTML, sound, animation, photography, programming with Processing, etc."
    am.innerHTML = "Bachelor of Multimedia Arts";
    año_am.innerHTML = "2022 / Present (First year finished)";
    universidad.innerHTML = "National University Of The Arts";
    cursoOracle.innerHTML = "Front-end developer course";
    añoCursoOracle.innerHTML = "2023 / Present";
    empresaCursoOracle.innerHTML = "ONE - Oracle Next Education in association with Alura Latam.";
    card2.innerHTML = "Completed formations: <hr> • Personal Development: <br> - Duration: 35 Hours <br> <hr> • Beginner in Programming. <br> - Duration: 75 Hours <br> <hr> • HTML & CSS. <br> - Duration: 65 Hours <br> <hr> • Business Agility. <br> - Duration: 26 Hours"
    card3.innerHTML = "Completed formations: <hr> • Introduction to Programming. <br> - Duration: 9 Hours <br> <hr> • Concepts of Programming. <br> - Duration: 9 Hours <br> <hr> • HTML and CSS. <br> - Duration: 17 Hours <br> <hr> • Basic JavaScript. <br> - Duration: 15 Hours <br> <hr> • TypeScript. <br> - Duration: 9 Hours"
    card4.innerHTML = "• High school completed on time with an overall GPA of 8.51 (eight point fifty-one). <br> • Bachelor's degree in Popular Theater."
    colegio.innerHTML = "Bachelor of Popular Theater";
    numero_colegio.innerHTML = "School n° 788";
    titulo_pagina.innerHTML = "<strong>Programming experience:</strong>";
    encriptador.innerHTML = "Text Encryptor";
    repositorio.innerHTML = "GitHub Repository";
    github.innerHTML = "GitHub Repository";
    titulo_conocimientos.innerHTML = "<strong>Skills:</strong>";
    curriculumSpanish.innerHTML = "English curriculum"
    curriculumEnglish.innerHTML = "Spanish curriculum"
    formularioTitulo.innerHTML = "<strong>Contact Form:</strong>"
    nameForm.innerHTML = "Name:"
    validForm.innerHTML = "Valid data"
    invalidForm.innerHTML = "Please write your name"
    emailForm.innerHTML = "Email:"
    validForm1.innerHTML = "Valid data"
    invalidForm1.innerHTML = "Please write your email"
    asuntoForm.innerHTML = "Subject:"
    validForm2.innerHTML = "Valid data"
    invalidForm2.innerHTML = "Please write the subject"
    mensajeForm.innerHTML = "Message:"
    validForm3.innerHTML = "Valid data"
    invalidForm3.innerHTML = "Please write your message"
    sendForm.innerHTML = " Send form "
  }
  
  function spanish() {
    document.getElementById("ingles").style.display = "inline";
    document.getElementById("español").style.display = "none";
    acercaDeMi.innerHTML = "Perfil profesional"
    educacionTitulo.innerHTML = "Educación"
    exp.innerHTML = "Experiencia Programacion"
    skill.innerHTML = "habilidades"
    contacto.innerHTML = "Contacto"
    cargo.innerHTML = "Estudiante de Ingenieria En Sistemas De Información";
    aboutMe.innerHTML = "<strong>Perfil profesional:</strong>"
    type.innerHTML = "Estudiante de tercer año de Ingeniería en Sistemas de Información en la UTN, con formación en programación, estructuras de datos, sistemas operativos y arquitectura de computadoras. Busco mi primera experiencia profesional en el área de sistemas para aplicar mis conocimientos, seguir desarrollando mis habilidades técnicas y contribuir al desarrollo de soluciones de software."
    card.innerHTML = "Hobbies: <br> - Disfruto mucho la musica y el deporte, gran apasionado del entrenamiento, ex tenista profesional.<br> - Apasionado de la cocina, disfruto pasar mis fines de semana leyendo y viendo peliculas/series. </br> <br> Soft skills:<br> • Flexibilidad, adaptacion al cambio<br> • Capacidad de comunicacion efectiva<br> • Resolucion de problemas<br> • Trabajo en equipo<br> • Proactividad<br> • Creatividad<br> • Pensamiento critico"
    educacionSeccion.innerHTML = "Educación:";
    card1.innerHTML = "• Primer año de la licenciatura finalizado con un promedio general de 8,17 (ocho con 17).<br> • En la licenciatura se estudian materias relacionadas al desarrollo web con JavaScript, CSS y HTML, sonido, animación, fotógrafia, programación con Processing, etc."
    am.innerHTML = "Licenciatura de Artes Multimediales";
    año_am.innerHTML = "2022 / Presente (Primer año finalizado)";
    universidad.innerHTML = "Universidad Nacional De Las Artes";
    cursoOracle.innerHTML = "Curso de desarrollador Front-End";
    añoCursoOracle.innerHTML = "Marzo 2023 - Septiembre 2023";
    empresaCursoOracle.innerHTML = "ONE - Oracle Next Education junto a Alura Latam.";
    card2.innerHTML = "Formaciones finalizadas: <hr> • Desarrollo personal.<br> - Duración: 35 Horas<br> <hr> • Principiante en programación.<br> - Duración: 75 Horas<br> <hr> • HTML & CSS.<br> - Duracion: 65 Horas<br> <hr> • Business Agility.<br> - Duracion: 26 Horas" 
    card3.innerHTML = " Formaciones finalizadas: <hr> • Introduccion a la programacion.<br> - Duración: 9 Horas<br> <hr> • Conceptos de la programacion.<br> - Duracion: 9 Horas<br> <hr> • HTML y CSS<br> - Duración: 17 Horas<br> <hr> • JavaScript Basico<br> - Duración: 15 Horas<br> <hr> • TypeScript<br> - Duracion: 9 Horas"
    card4.innerHTML = "• Colegio secundario finalizado en tiempo y forma con un promedio general de 8.51 (Ocho con cincuenta y uno) <br> • Bachillerato en teatro popular"
    colegio.innerHTML = "Bachiller en Teatro Popular";
    numero_colegio.innerHTML = "Colegio n° 788";
    titulo_pagina.innerHTML = "<strong>Experiencia en programacion:</strong>";
    encriptador.innerHTML = "Encriptador De Texto";
    repositorio.innerHTML = "Repositorio de GitHub";
    github.innerHTML = "Repositorio de GitHub";
    titulo_conocimientos.innerHTML = "<strong>Habilidades:</strong";
    curriculumSpanish.innerHTML = "Curriculum en Español"
    curriculumEnglish.innerHTML = "Curriculum en Ingles"
    formularioTitulo.innerHTML = "<strong>Formulario de contacto:</strong>"
    nameForm.innerHTML = "Nombre:"
    validForm.innerHTML = "Dato valido"
    invalidForm.innerHTML = "Por favor escriba su nombre"
    emailForm.innerHTML = "Correo electronico:"
    validForm1.innerHTML = "Dato valido"
    invalidForm1.innerHTML = "Por favor escriba su correo electronico"
    asuntoForm.innerHTML = "Asunto"
    validForm2.innerHTML = "Dato valido"
    invalidForm2.innerHTML = "Por favor escriba el asunto"
    mensajeForm.innerHTML = "Mensaje:"
    validForm3.innerHTML = "Dato valido"
    invalidForm3.innerHTML = "Por favor escriba su mensaje"
    sendForm.innerHTML = " Enviar formulario "
  }
  